#!/bin/sh

. /etc/settings.sh
. /etc/functions.sh

for mod in $BASE_MODULES; do
    log "Loading module '$mod'."
    modprobe $mod
done

#for mod in $(ls /lib/modules/$(uname -r)/kernel/crypto | sed 's/\.ko//'); do
#    log "Loading crypto module '$mod'."
#    modprobe $mod
#done
